version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/root
    environment:
      MEILISEARCH_HOST: ${MEILISEARCH_HOST}
      MEILISEARCH_API_KEY: ${MEILISEARCH_API_KEY}
    networks:
      - cine-quest-network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/root
    networks:
      - cine-quest-network

networks:
  cine-quest-network:
    driver: bridge
